# This is a basic workflow to help you get started with Actions

name: CI


on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # or your required version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: bash scripts/build_docker.sh

      - name: Install CDK dependencies
        run: |
          cd cdk-app
          pip install poetry
          poetry install

      - name: CDK Synth
        run: |
          cd cdk-app
          poetry run python scripts/build_cdk.py

      - name: CDK Deploy
        run: |
          cd cdk-app
          poetry run cdk deploy --all --require-approval never
      
